# .github/workflows/github-stats.yml

name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule to run daily, adjust as needed

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Update GitHub Stats
        run: node update-github-stats.js
